import { describe, expect, it } from "vitest";
import { generateRecommendations, historicalJackpotKeys, isHistoricalJackpot, normalizeRequest, rankCombination, excludeHistoricalJackpots, uniqueByCombination } from "./index.js";
import type { DrawResult } from "@lotto/shared";
const draws: DrawResult[] = [ { drawNo: 1, date: "2002-12-07", numbers: [10,23,29,33,37,40], bonusNumber: 16, parserVersion: "seed" }, { drawNo: 2, date: "2002-12-14", numbers: [9,13,21,25,32,42], bonusNumber: 2, parserVersion: "seed" } ];
describe("core generation", () => {
  it("includes lucky numbers, returns ascending unique non-jackpot picks", () => { const out = generateRecommendations({ luckyNumbers: [7,11], count: 5, historicalDraws: draws, targetDrawNo: 3 }); expect(out.recommendations).toHaveLength(5); const keys = new Set<string>(); for (const r of out.recommendations) { expect(r.numbers).toEqual([...r.numbers].sort((a,b)=>a-b)); expect(r.numbers).toContain(7); expect(r.numbers).toContain(11); expect(isHistoricalJackpot(r.numbers, historicalJackpotKeys(draws))).toBe(false); keys.add(r.numbers.join('-')); } expect(keys.size).toBe(5); });
  it("reports infeasible six lucky jackpot as HTTP-friendly feasibility", () => { const out = generateRecommendations({ luckyNumbers: [10,23,29,33,37,40], count: 5, historicalDraws: draws, targetDrawNo: 3 }); expect(out.recommendations).toHaveLength(0); expect(out.feasibility.status).toBe("INFEASIBLE_LUCKY_SET"); });
  it("forces six lucky non-jackpot to one", () => { const out = generateRecommendations({ luckyNumbers: [1,2,3,4,5,6], count: 5, historicalDraws: draws, targetDrawNo: 3 }); expect(out.recommendations).toHaveLength(1); expect(out.recommendations[0].numbers).toEqual([1,2,3,4,5,6]); });
  it("normalizes and clamps count", () => expect(normalizeRequest({ luckyNumbers: [11,7], count: 99 }).count).toBe(5));
  it("exclusion helpers filter jackpots and duplicates", () => { const keys = historicalJackpotKeys(draws); expect(excludeHistoricalJackpots([{numbers: draws[0].numbers}, {numbers: [1,2,3,4,5,6]}], keys)).toHaveLength(1); expect(uniqueByCombination([{numbers:[1,2,3,4,5,6]}, {numbers:[6,5,4,3,2,1]}])).toHaveLength(1); });
});
describe("rank", () => { const draw = [1,2,3,4,5,6], bonus = 7; it.each([ [[1,2,3,4,5,6], "1st", false], [[1,2,3,4,5,7], "2nd", true], [[1,2,3,4,5,8], "3rd", false], [[1,2,3,4,8,9], "4th", false], [[1,2,3,8,9,10], "5th", false], [[1,2,8,9,10,11], "No Prize", false] ] as const)("ranks %o as %s", (pick, rank, bonusMatched) => { const result = rankCombination([...pick], draw, bonus); expect(result.rank).toBe(rank); expect(result.bonusMatched).toBe(bonusMatched); }); });
