import type { DrawResult, Recommendation } from "@lotto/shared";
import { assessFeasibility } from "./feasibility.js";
import { historicalJackpotKeys, isHistoricalJackpot, uniqueByCombination } from "./exclusion.js";
import { computeCandidateStats } from "./statistics.js";
import { tagsForStats } from "./tags.js";
import { fallbackExplanation } from "./fallback.js";
function candidateScore(numbers: number[]): number { const stats = computeCandidateStats(numbers); return Math.abs(3 - stats.odd) * 8 + stats.consecutivePairs * 4 + stats.sameEndingPairs * 2 + Math.abs(135 - stats.sum) / 12 + Math.abs(2 - stats.low) + Math.abs(2 - stats.mid) + Math.abs(2 - stats.high); }
function lcg(seed: number) { let s = seed >>> 0; return () => ((s = (1664525 * s + 1013904223) >>> 0) / 4294967296); }
function makeCandidate(luckyNumbers: number[], attempt: number, targetDrawNo: number): number[] { const pool = Array.from({length:45}, (_,i)=>i+1).filter(n=>!luckyNumbers.includes(n)); const rand = lcg((targetDrawNo * 1009) + attempt * 9176 + luckyNumbers.reduce((a,b)=>a+b*31,0)); const chosen = [...luckyNumbers]; while (chosen.length < 6) { const idx = Math.floor(rand() * pool.length); const [n] = pool.splice(idx, 1); chosen.push(n); } return chosen.sort((a,b)=>a-b); }
export function generateRecommendations(opts: { luckyNumbers: number[]; count: number; historicalDraws: DrawResult[]; targetDrawNo: number }): { recommendations: Recommendation[]; feasibility: ReturnType<typeof assessFeasibility>["feasibility"] } { const jackpotKeys = historicalJackpotKeys(opts.historicalDraws); const { effectiveCount, feasibility } = assessFeasibility(opts.luckyNumbers, opts.count, jackpotKeys); if (feasibility.status === "INFEASIBLE_LUCKY_SET" || effectiveCount === 0) return { recommendations: [], feasibility }; if (opts.luckyNumbers.length === 6) { const numbers = [...opts.luckyNumbers].sort((a,b)=>a-b); const stats = computeCandidateStats(numbers, opts.historicalDraws.length); const tags = tagsForStats(stats); const fb = fallbackExplanation(numbers, tags, opts.luckyNumbers); return { recommendations: [{ id: "rec_1", numbers, tags, stats, ...fb }], feasibility }; } const candidates: { numbers: number[]; score: number }[] = []; for (let attempt=0; candidates.length < effectiveCount * 8 && attempt < 5000; attempt++) { const numbers = makeCandidate(opts.luckyNumbers, attempt, opts.targetDrawNo); if (!isHistoricalJackpot(numbers, jackpotKeys)) candidates.push({ numbers, score: candidateScore(numbers) }); } const unique = uniqueByCombination(candidates).sort((a,b)=>a.score-b.score).slice(0, effectiveCount); return { recommendations: unique.map((c, i) => { const stats = computeCandidateStats(c.numbers, opts.historicalDraws.length); const tags = tagsForStats(stats); return { id: `rec_${i+1}`, numbers: c.numbers, tags, stats, ...fallbackExplanation(c.numbers, tags, opts.luckyNumbers) }; }), feasibility }; }
